CREATE TABLE tutorials_tbl
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    author VARCHAR(20) NOT NULL
);

INSERT INTO tutorials_tbl(title, author)
values ('Learn PHP', 'John Poul');

INSERT INTO tutorials_tbl(title, author)
values ('Learn MySQL', 'Abdul S');

INSERT INTO tutorials_tbl(title, author)
values ('Learn Java', 'Sanjay');

INSERT INTO tutorials_tbl(title, author)
values ('Learn Hibernate', 'Yogesh');

INSERT INTO tutorials_tbl(title, author)
values ('Learn Struts', 'Sanjay');
